[workspace]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>", "Ruben Arts", "John Kirkham"]
channels = ["conda-forge"]
name = "reproducible-ml-for-scientists-with-pixi-scipy-2025"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks.start]
cmd = "cd book && myst start"

[tasks.lint]
description = "Run pre-commit on all files in the repository"
cmd = "pre-commit run --all-files"

[dependencies]
mystmd = ">=1.3.26,<2"
pre-commit = ">=4.2.0,<5"
